# gRPC server configuration
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=true

# HTTP server configuration
quarkus.http.port=8080

# Container image configuration
quarkus.container-image.registry=registry.ultra.lab
quarkus.container-image.group=default
quarkus.container-image.name=quarkus-grpc
quarkus.container-image.tag=latest
quarkus.container-image.builder=jib

# Application name
quarkus.application.name=quarkus-grpc
